[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "./renode-runner.sh"
rustflags = [
    "-C", "link-arg=-Tlink.x",   # cortex-m-rt's linker script
    "-C", "target-cpu=cortex-m4",
]
